/*
 * File: app/store/Gender.js
 *
 * This file was generated by Sencha Architect version 3.0.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyAppOne.store.Gender', {
    extend: 'Ext.data.Store',

    requires: [
        'MyAppOne.model.Gender'
    ],

    config: {
        data: [
            {
                id: 'Id 1',
                name: 'male'
            },
            {
                id: 'Id 2',
                name: 'female'
            }
        ],
        model: 'MyAppOne.model.Gender',
        storeId: 'Gender'
    }
});