/*
 * File: app/view/MainView.js
 *
 * This file was generated by Sencha Architect version 3.0.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyAppOne.view.MainView', {
    extend: 'Ext.Container',
    alias: 'widget.Mainview',

    requires: [
        'Ext.TitleBar',
        'Ext.tab.Panel',
        'Ext.form.Panel',
        'Ext.form.FieldSet',
        'Ext.field.Select',
        'Ext.field.TextArea',
        'Ext.tab.Bar'
    ],

    config: {
        layout: 'fit',
        items: [
            {
                xtype: 'titlebar',
                docked: 'top',
                hideOnMaskTap: false,
                title: 'MyAppOne'
            },
            {
                xtype: 'tabpanel',
                items: [
                    {
                        xtype: 'container',
                        title: 'Main',
                        iconCls: 'home',
                        centered: false,
                        layout: 'fit',
                        items: [
                            {
                                xtype: 'formpanel',
                                centered: false,
                                html: 'Welcome to our first app :)',
                                padding: 25,
                                styleHtmlContent: true,
                                layout: 'fit'
                            }
                        ]
                    },
                    {
                        xtype: 'panel',
                        title: 'List',
                        iconCls: 'arrow_up',
                        layout: 'fit',
                        modal: false,
                        items: [
                            {
                                xtype: 'formpanel',
                                layout: 'fit',
                                items: [
                                    {
                                        xtype: 'fieldset',
                                        title: 'You',
                                        items: [
                                            {
                                                xtype: 'textfield',
                                                label: 'Name',
                                                name: 'name'
                                            },
                                            {
                                                xtype: 'textfield',
                                                label: 'Age',
                                                name: 'age'
                                            },
                                            {
                                                xtype: 'selectfield',
                                                label: 'Gender',
                                                name: 'gender',
                                                displayField: 'name',
                                                store: 'Gender',
                                                valueField: 'id'
                                            }
                                        ]
                                    }
                                ]
                            }
                        ]
                    },
                    {
                        xtype: 'container',
                        title: 'Tab 3',
                        iconCls: 'info',
                        layout: 'fit',
                        items: [
                            {
                                xtype: 'textareafield',
                                label: 'Feedback'
                            }
                        ]
                    }
                ],
                tabBar: {
                    docked: 'bottom',
                    ui: 'light',
                    layout: {
                        type: 'hbox',
                        pack: 'center'
                    }
                }
            }
        ]
    }

});